name: Build ONNX Runtime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

env:
  ONNXRUNTIME_VERSION: v1.21.0

jobs:
  build-onnxruntime:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/onnxruntime
          ref: ${{ env.ONNXRUNTIME_VERSION }}

      - name: Cache ONNX Runtime
        id: cache-onnxruntime
        uses: actions/cache@v4
        with:
          path: onnxruntime
          key: onnxruntime-${{ env.ONNXRUNTIME_VERSION }}

      - name: Build ONNX Runtime
        run: .\build.bat --build_dir onnxruntime\build\Windows ^
          --config Release --parallel --skip_tests ^
          --enable_msvc_static_runtime ^
          --cmake_generator "Visual Studio 17 2022"
